# Variables
@baseUrl = http://localhost:3333

# Health check 

GET {{baseUrl}}/health

###

# Get rooms
# @name getRoom
GET {{baseUrl}}/rooms

### 

# Create room 
# @name createRoom

POST {{baseUrl}}/rooms 
Content-Type: application/json

{
    "name": "Sala de teste", 
    "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions

GET {{baseUrl}}/rooms/12ab7d71-5f85-4bd7-9f3a-d5df885be795/questions

### 

# Create question 
# @name createQuestion

POST {{baseUrl}}/rooms/12ab7d71-5f85-4bd7-9f3a-d5df885be795/questions 
Content-Type: application/json

{
    "question": "O que é Java? E qual sua diferença com o Go?"
}